const test = require("node:test");
const assert = require("node:assert/strict");
const { migrateState, companyContext } = require("../commercial-core");

test("commercial migration is additive, idempotent and separates company website from sample URL", () => { const state = { proposals: [{ id: "p1", companyName: "Empresa", clientName: "Ana", clientEmail: "ana@empresa.pt", clientPhone: "912345678", status: "Orçamento enviado", leadSource: "Instagram", sampleUrl: "https://clientes.uneed.pt/amostra", services: [], activities: [{ id: "a1", type: "Contacto", note: "Telefonema", createdAt: "2026-09-01T10:00:00Z" }], createdAt: "2026-09-01T09:00:00Z", updatedAt: "2026-09-01T10:00:00Z" }], instagramProspects: [], contracts: [], tickets: [] }; migrateState(state); const counts = [state.companies.length,state.contacts.length,state.leads.length,state.opportunities.length,state.activities.length]; migrateState(state); assert.deepEqual([state.companies.length,state.contacts.length,state.leads.length,state.opportunities.length,state.activities.length], counts); assert.equal(state.companies[0].website, ""); assert.equal(state.proposals[0].sampleUrl, "https://clientes.uneed.pt/amostra"); assert.equal(state.proposals[0].companyWebsite, ""); assert.equal(state.leads[0].source, "instagram_prospecting"); assert.equal(state.opportunities[0].stage, "PROPOSAL"); });

test("Instagram prospect and proposal share a company only on a strong identity signal", () => { const state = { proposals: [{ id: "p1", companyName: "Empresa", clientPhone: "+351 912 345 678", status: "Novo pedido", services: [], activities: [] }], instagramProspects: [{ id: "ig1", name: "Empresa", phone: "912345678", instagramUrl: "https://instagram.com/empresa", status: "Por fazer" }], contracts: [], tickets: [] }; migrateState(state); assert.equal(state.companies.length, 1); assert.equal(state.proposals[0].companyId, state.instagramProspects[0].companyId); assert.equal(state.instagramProspects[0].leadId, state.leads.find((item) => item.legacyInstagramProspectId === "ig1").id); });

test("ambiguous same-name companies are not merged", () => { const state = { proposals: [{ id: "p1", companyName: "Empresa", clientEmail: "a@empresa-a.pt", status: "Novo pedido", services: [], activities: [] }], instagramProspects: [{ id: "ig1", name: "Empresa", phone: "919999999", status: "Por fazer" }], contracts: [], tickets: [] }; migrateState(state); assert.equal(state.companies.length, 2); assert.deepEqual(state.companies[1].potentialDuplicateOf, [state.companies[0].id]); });

test("company context resolves Company and Lead without Proposal", () => { const state = { proposals: [], instagramProspects: [{ id: "ig1", name: "Empresa", website: "https://empresa.pt", status: "Por fazer" }], contracts: [], tickets: [] }; migrateState(state); const context = companyContext(state, state.instagramProspects[0].leadId); assert.equal(context.company.website, "https://empresa.pt/"); assert.equal(context.lead.source, "instagram_prospecting"); assert.equal(context.contact, null); });
