const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const { isPrivateIp, validatePublicUrl, fetchPublicUrl, extractPage } = require("../uneed-os/public-web");
const { PageClient } = require("../uneed-os/discover-tools");
const { DiscoverService } = require("../uneed-os/discover");
const { OpenAIWebSearchProvider, BraveSearchProvider } = require("../uneed-os/web-search");

const html = fs.readFileSync(path.join(__dirname, "fixtures/company.html"), "utf8");
const publicLookup = async () => [{ address: "93.184.216.34", family: 4 }];

test("URL validation accepts only public HTTP(S) and blocks SSRF ranges", async () => { assert.equal(isPrivateIp("127.0.0.1"), true); assert.equal(isPrivateIp("10.2.3.4"), true); assert.equal(isPrivateIp("169.254.169.254"), true); assert.equal(isPrivateIp("93.184.216.34"), false); await assert.rejects(() => validatePublicUrl("file:///etc/passwd"), /não permitido/); await assert.rejects(() => validatePublicUrl("http://localhost/admin"), /interno/); await assert.rejects(() => validatePublicUrl("http://example.test", async () => [{ address: "192.168.1.2", family: 4 }]), /privada/); assert.equal((await validatePublicUrl("https://example.com", publicLookup)).address, "93.184.216.34"); });

test("redirects are revalidated and capped", async () => { let calls = 0; const requester = async () => { calls += 1; return calls === 1 ? { status: 302, headers: { location: "http://127.0.0.1/secret" }, body: "" } : { status: 200, headers: { "content-type": "text/html" }, body: html }; }; await assert.rejects(() => fetchPublicUrl("https://example.com", { lookup: publicLookup, requester }), /privad|bloquead/); assert.equal(calls, 1); const looping = async () => ({ status: 302, headers: { location: "/again" }, body: "" }); await assert.rejects(() => fetchPublicUrl("https://example.com", { lookup: publicLookup, requester: looping, maxRedirects: 1 }), /Redirect/); });

test("content normalisation extracts useful signals and removes scripts", () => { const page = extractPage(html, "https://example.com/"); assert.equal(page.title, "Clínica Exemplo"); assert.equal(page.viewport, true); assert.equal(page.forms, 1); assert.match(page.text, /Consultas/); assert.doesNotMatch(page.text, /private/); assert.ok(page.links.some((item) => item.url === "https://example.com/contactos")); });

test("Discover builds evidence-first Research Pack with limits, unknowns and social profiles", async () => { let searches = 0; let fetches = 0; const searchProvider = { supports: () => true, estimateCost: () => 0.01, search: async () => { searches += 1; return { results: [{ title: "Clínica", url: "https://example.com/", snippet: "Clínica", source: "fixture", publishedAt: null }], cost: 0.01, costStatus: "actual" }; } }; const pageClient = new PageClient({ fetcher: async (url) => { fetches += 1; return { finalUrl: url, status: 200, headers: { "content-type": "text/html" }, body: html, redirects: [] }; } }); const service = new DiscoverService({ searchProvider, pageClient, limits: { maxSearches: 1, maxPages: 2, maxDepth: 1 } }); const result = await service.research({ companyName: "Clínica Exemplo", clientEmail: "crm@example.test", services: [{ name: "Uneed Presença", selected: true }] }, { budget: 1 }); assert.equal(searches, 1); assert.ok(fetches <= 2); assert.equal(result.pack.schemaVersion, "1.0.0"); assert.ok(result.pack.evidence.every((item) => item.id && item.observedAt && item.fact)); assert.ok(result.pack.unknowns.includes("Orçamento disponível")); assert.equal(result.pack.digitalPresence.socialProfiles[0].platform, "instagram"); assert.equal(new Set(result.pack.evidence.map((item) => `${item.sourceUrl}:${item.fact}`)).size, result.pack.evidence.length); });

test("partial source failure yields warnings rather than invented facts", async () => { const service = new DiscoverService({ searchProvider: { supports: () => false }, pageClient: new PageClient({ fetcher: async () => { throw new Error("offline"); } }) }); const result = await service.research({ companyName: "Sem Site", sampleUrl: "https://example.com" }); assert.equal(result.partial, true); assert.equal(result.pack.confidence, "low"); assert.ok(result.pack.unknowns.includes("Estado técnico atual do website")); assert.equal(result.pack.evidence.length, 0); });

test("web search timeout produces an explicit partial Research Pack instead of failing the Mission", async () => { const timeout = Object.assign(new Error("timeout"), { code: "AI_TIMEOUT", retryable: true }); const searchProvider = { supports: () => true, estimateCost: () => 0.01, search: async () => { throw timeout; } }; const service = new DiscoverService({ searchProvider, limits: { maxSearches: 1, maxPages: 1 } }); const result = await service.research({ companyName: "Empresa Lenta" }, { budget: 1 }); assert.equal(result.partial, true); assert.equal(result.pack.companyIdentity.name, "Empresa Lenta"); assert.ok(result.pack.warnings.some((item) => item.includes("AI_TIMEOUT"))); assert.equal(result.pack.digitalPresence.website, null); });

test("search/tool budget is enforced before paid query", async () => { let calls = 0; const provider = { supports: () => true, estimateCost: () => 2, search: async () => { calls += 1; return { results: [] }; } }; const service = new DiscoverService({ searchProvider: provider }); await assert.rejects(() => service.research({ companyName: "Teste" }, { budget: 1 }), /Orçamento estimado/); assert.equal(calls, 0); });

test("conflicting public and CRM contacts remain unresolved and reduce confidence", async () => { const searchProvider = { supports: () => false }; const pageClient = new PageClient({ fetcher: async (url) => ({ finalUrl: url, status: 200, headers: { "content-type": "text/html" }, body: html, redirects: [] }) }); const result = await new DiscoverService({ searchProvider, pageClient }).research({ companyName: "Clínica", companyWebsite: "https://example.com", clientEmail: "different@example.test" }); assert.equal(result.pack.knownData.contacts.email, null); assert.equal(result.pack.conflicts[0].field, "email"); assert.ok(result.pack.unknowns.some((item) => item.includes("conflito"))); assert.notEqual(result.pack.confidence, "high"); });

test("DISCOVER never treats a Proposal sample URL as the company website", async () => { let fetches = 0; const service = new DiscoverService({ searchProvider: { supports: () => false }, pageClient: new PageClient({ fetcher: async () => { fetches += 1; throw new Error("should not fetch"); } }) }); const result = await service.research({ companyName: "Empresa", sampleUrl: "https://clientes.uneed.pt/amostra" }); assert.equal(fetches, 0); assert.equal(result.pack.digitalPresence.website, null); assert.ok(result.pack.warnings.includes("Website oficial não confirmado.")); });

test("DISCOVER keeps Racius as external reference and leaves official website empty", async () => { let fetches = 0; const searchProvider = { supports: () => true, estimateCost: () => 0, search: async () => ({ results: [{ title: "Diretório", url: "https://racius.com/empresa/teste", snippet: "Empresa", source: "openai" }], cost: 0, costStatus: "actual" }) }; const service = new DiscoverService({ searchProvider, pageClient: new PageClient({ fetcher: async () => { fetches += 1; throw new Error("should not fetch directory"); } }), limits: { maxSearches: 1 } }); const result = await service.research({ companyName: "Empresa" }); assert.equal(fetches, 0); assert.equal(result.pack.digitalPresence.website, null); assert.equal(result.pack.externalReferences[0].type, "external_reference"); });

test("Brave adapter sends server-side token and normalises official response shape", async () => { let request; const provider = new BraveSearchProvider({ apiKey: "test-secret", fetchImpl: async (url, options) => { request = { url: String(url), options }; return { ok: true, status: 200, json: async () => ({ web: { results: [{ title: "Empresa", url: "https://empresa.pt", description: "Resumo", page_age: "2026-09-01" }] } }) }; }, costPerQuery: 0.01 }); const result = await provider.search({ query: "Empresa", maxResults: 5 }); assert.equal(request.options.headers["X-Subscription-Token"], "test-secret"); assert.match(request.url, /api\.search\.brave\.com/); assert.deepEqual(result.results[0], { title: "Empresa", url: "https://empresa.pt", snippet: "Resumo", source: "brave", publishedAt: "2026-09-01" }); });

test("OpenAI adapter uses Responses web_search and preserves the normalised result and cost shape", async () => { let request; const provider = new OpenAIWebSearchProvider({ apiKey: "test-secret", model: "gpt-5-mini", fetchImpl: async (url, options) => { request = { url, options, body: JSON.parse(options.body) }; return { ok: true, status: 200, json: async () => ({ output: [{ type: "web_search_call", action: { type: "search", sources: [{ title: "Empresa", url: "https://empresa.pt" }] } }, { type: "message", content: [{ type: "output_text", text: "A Empresa presta serviços digitais.", annotations: [{ type: "url_citation", start_index: 0, end_index: 35, title: "Empresa", url: "https://empresa.pt" }] }] }], usage: { input_tokens: 100, output_tokens: 20 } }) }; }, costPerQuery: 0.01, inputCostPerMillion: 1, outputCostPerMillion: 2, maxQueryCost: 0.05 }); const result = await provider.search({ query: "Empresa", maxResults: 5 }); assert.equal(request.url, "https://api.openai.com/v1/responses"); assert.equal(request.options.headers.Authorization, "Bearer test-secret"); assert.deepEqual(request.body.tools, [{ type: "web_search" }]); assert.deepEqual(request.body.include, ["web_search_call.action.sources"]); assert.equal(request.body.max_tool_calls, 1); assert.deepEqual(result.results[0], { title: "Empresa", url: "https://empresa.pt", snippet: "A Empresa presta serviços digitais.", source: "openai", publishedAt: null }); assert.equal(result.costStatus, "actual"); assert.equal(result.cost, 0.01014); });

test("OpenAI web search is bounded for the serverless worker budget", async () => { let body; const provider = new OpenAIWebSearchProvider({ apiKey: "test-secret", fetchImpl: async (_url, options) => { body = JSON.parse(options.body); return { ok: true, status: 200, json: async () => ({ output: [{ type: "web_search_call", action: { sources: [{ title: "Empresa", url: "https://empresa.pt" }] } }, { type: "message", content: [{ type: "output_text", text: "Resumo", annotations: [] }] }], usage: {} }) }; } }); await provider.search({ query: "Empresa" }); assert.deepEqual(body.reasoning, { effort: "low" }); assert.deepEqual(body.text, { verbosity: "low" }); assert.equal(body.max_output_tokens, 600); assert.equal(body.store, false); });

test("OpenAI adapter keeps actual cost unknown when pricing is not configured", async () => { const provider = new OpenAIWebSearchProvider({ apiKey: "test-secret", fetchImpl: async () => ({ ok: true, status: 200, json: async () => ({ output: [{ type: "web_search_call", action: { sources: [{ title: "Empresa", url: "https://empresa.pt" }] } }, { type: "message", content: [{ type: "output_text", text: "Resumo", annotations: [] }] }], usage: { input_tokens: 10, output_tokens: 5 } }) }) }); const result = await provider.search({ query: "Empresa" }); assert.equal(result.cost, null); assert.equal(result.costStatus, "unknown"); assert.equal(provider.estimateCost(), 0.05); });
