const {test}=require('node:test'),assert=require('node:assert/strict'),sharp=require('sharp');
const I=require('../kickoffs/images'),M=require('../kickoffs/model');
const valid=()=>sharp({create:{width:24,height:16,channels:3,background:'#ee3344'}}).png().toBuffer();
function fixture(){
  let state=M.create('owner',{product:'presenca',plan:'presenca-essencial',company:'Teste',contact:'Teste',email:'test@example.com',vat:0,retention:0,initialBase:0,paymentMethod:'bank_transfer'});M.issue(state,'secret');
  const files=new Map(),signed=[];
  const repo={cfg:{},get:async()=>structuredClone(state),save:async(row,revision)=>{if(revision!==state.revision)M.fail('Conflict',409);state=structuredClone({...row,revision:revision+1});return structuredClone(state);}};
  const storage={createSignedUploadUrl:async(path,options)=>{signed.push({path,options});return {data:{signedUrl:'https://storage.example/'+path}};},
    download:async path=>files.has(path)?{data:new Blob([files.get(path)])}:{error:'not found'},
    upload:async(path,bytes)=>{if(files.has(path))return {error:'exists'};files.set(path,Buffer.from(bytes));return {data:{path}};},
    createSignedUrl:async(path,seconds,options)=>{signed.push({path,seconds,options});return {data:{signedUrl:'https://storage.example/download'}};}};
  const run=body=>I.run(repo,structuredClone(state),{revision:state.revision,...body},'customer',storage);
  return {run,files,signed,get:()=>state,set:r=>{state=r;}};
}
test('PNG validation decodes content and retains original bytes/hash',async()=>{const bytes=await valid(),copy=Buffer.from(bytes),meta=await I.validate(bytes,'image/png');assert.equal(meta.width,24);assert.equal(meta.height,16);assert.deepEqual(bytes,copy);assert.equal(meta.size,bytes.length);});
test('JPEG and WebP are valid; declared MIME must match real format',async()=>{for(const [format,mime] of [['jpeg','image/jpeg'],['webp','image/webp']]){const bytes=await sharp(await valid()).toFormat(format).toBuffer();assert.equal((await I.validate(bytes,mime)).width,24);}await assert.rejects(I.validate(await valid(),'image/jpeg'));});
test('SVG scripts, renamed HTML, truncated PNG, empty and oversized uploads are rejected',async()=>{for(const bytes of [Buffer.from('<svg onload="alert(1)"></svg>'),Buffer.from('<html>not an image</html>'),(await valid()).subarray(0,25),Buffer.alloc(0),Buffer.alloc(I.MAX_FILE+1)])await assert.rejects(I.validate(bytes,'image/png'));});
test('signed upload cannot overwrite another object and filename never controls path',async()=>{const f=fixture(),r=await f.run({action:'image-reserve',name:'../../evil<script>.png',mime:'image/png',size:98});assert.equal(f.signed[0].options.upsert,false);assert.match(f.signed[0].path,/^owner\/[a-f0-9-]+\/[a-f0-9-]+\/incoming.png$/);assert.ok(!r.row.data.images[0].name.includes('<'));});
test('quota reserves worst-case bytes, bounding incomplete uploads',async()=>{const f=fixture();for(let n=0;n<5;n++)await f.run({action:'image-reserve',name:'a.png',mime:'image/png',size:1});await assert.rejects(f.run({action:'image-reserve',name:'a.png',mime:'image/png',size:1}),/Limite/);});
test('only validated originals get download links with attachment and 60 second TTL',async()=>{const f=fixture(),bytes=await valid();let r=await f.run({action:'image-reserve',name:'foto.png',mime:'image/png',size:bytes.length});const file=r.row.data.images[0];await assert.rejects(f.run({action:'image-download',fileId:file.id}),/indisponível/);f.files.set(file.incoming,bytes);r=await f.run({action:'image-finish',fileId:file.id});assert.equal(r.row.data.images[0].status,'ready');assert.deepEqual(f.files.get(file.path),bytes);await f.run({action:'image-download',fileId:file.id});const last=f.signed.at(-1);assert.equal(last.seconds,60);assert.equal(last.options.download,'foto.png');assert.equal(last.path,file.path);});
test('corrupt file is quarantined and cannot be downloaded',async()=>{const f=fixture(),r=await f.run({action:'image-reserve',name:'bad.png',mime:'image/png',size:5}),file=r.row.data.images[0];f.files.set(file.incoming,Buffer.from('hello'));const done=await f.run({action:'image-finish',fileId:file.id});assert.equal(done.row.data.images[0].status,'rejected');assert.equal(f.files.has(file.path),false);await assert.rejects(f.run({action:'image-download',fileId:file.id}));});
test('public projection omits Storage paths and validation checksums',async()=>{const f=fixture();await f.run({action:'image-reserve',name:'safe.png',mime:'image/png',size:98});const p=M.publicView(f.get());assert.ok(p.images.length);assert.equal(p.images[0].path,undefined);assert.equal(p.images[0].incoming,undefined);assert.equal(p.images[0].sha256,undefined);});
test('unknown file IDs never receive a download URL',async()=>{const f=fixture();await assert.rejects(f.run({action:'image-download',fileId:'other-kickoff-file'}));assert.equal(f.signed.length,0);});
test('completion is blocked while image validation/upload is pending',async()=>{const f=fixture();await f.run({action:'image-reserve',name:'safe.png',mime:'image/png',size:98});const r=f.get();r.data.submittedAt='now';r.data.checks={payment:true,debit:true,content:true,validated:true};assert.equal(M.complete(r),false);});
test('crash recovery accepts immutable copy only when content hash matches',async()=>{const f=fixture(),bytes=await valid(),r=await f.run({action:'image-reserve',name:'safe.png',mime:'image/png',size:bytes.length}),file=r.row.data.images[0];f.files.set(file.incoming,bytes);f.files.set(file.path,bytes);const done=await f.run({action:'image-finish',fileId:file.id});assert.equal(done.row.data.images[0].status,'ready');});
