const test = require("node:test");
const assert = require("node:assert/strict");
const { SERVICE_CATALOG, classifyUrl, scoreLead, selectChannels, buildLeadIntelligence, formatStructuredValue } = require("../lead-intelligence");

test("official websites are separated from directories and social profiles", () => { assert.equal(classifyUrl("https://empresa.pt").type, "official_website"); assert.equal(classifyUrl("https://racius.com/empresa/x").official, false); assert.equal(classifyUrl("https://instagram.com/empresa").type, "social_profile"); assert.equal(classifyUrl("https://fresha.com/a/empresa").type, "booking_profile"); });

test("commercial score is single, explainable and versioned", () => { const result = scoreLead({ placeId: "p1", niche: "Cabeleireiros", municipality: "Aveiro", phone: "912345678", instagramUrl: "https://instagram.com/test", website: "", reviewCount: 25 }); assert.equal(result.score, Object.values(result.breakdown).reduce((sum, value) => sum + value, 0)); assert.equal(result.version, "lead-intelligence-v0.1"); assert.ok(result.score >= 70); });

test("channel selection prefers the natural available channel", () => { assert.deepEqual(selectChannels({ instagramUrl: "https://instagram.com/test", phone: "912345678" }), { primaryChannel: "instagram", fallbackChannel: "whatsapp" }); assert.deepEqual(selectChannels({ phone: "912345678" }), { primaryChannel: "whatsapp", fallbackChannel: "phone" }); });

test("Lead Intelligence prepares one message policy, two follow-ups and a contextual mockup prompt", () => { const lead = buildLeadIntelligence({ name: "Salão Aveiro", niche: "Cabeleireiros", municipality: "Aveiro", placeId: "p1", phone: "912345678", website: "", hasBooking: false }, [{ name: "Uneed Presença" }]); assert.equal(lead.createdBy, "automated_lead_factory"); assert.equal(lead.readiness, "researching"); assert.match(lead.initialMessage, /Sou o Francisco, da Uneed Soluções Digitais/); assert.ok(lead.followUp1 && lead.followUp2); assert.match(lead.mockupPrompt, /Salão Aveiro/); assert.equal(lead.recommendedService, "Uneed Presença"); });

test("directory URL remains an external reference and never an official website", () => { const lead = buildLeadIntelligence({ name: "Empresa", website: "https://racius.com/empresa/test" }, []); assert.equal(lead.officialWebsite, null); assert.equal(lead.externalReferences[0].type, "external_reference"); });

test("official catalog is the only source for the local-business recommendation", () => { const lead = buildLeadIntelligence({ name: "Barbearia Central", niche: "Barbearias", phone: "912345678", website: "https://barbearia.pt", hasBooking: false, hasCta: false }, [{ name: "LEADS START" }]); assert.equal(lead.serviceId, "uneed_presence"); assert.equal(lead.recommendedService, SERVICE_CATALOG.uneed_presence.name); assert.doesNotMatch(JSON.stringify(lead), /LEADS START|Digital Starter|Presence Basic/); assert.equal(lead.serviceDetails.priceFrom, 39); });

test("commercial calibration separates confirmed gaps, improvement opportunities and unknowns", () => { const lead = buildLeadIntelligence({ name: "Barbearia Central", niche: "Barbearias", confirmedBusiness: true, phone: "912345678", website: "https://barbearia.pt", hasBooking: false, hasCta: false }); assert.ok(lead.confirmedGaps.some((item) => /marcação/.test(item.label))); assert.ok(lead.improvementOpportunities.length); assert.ok(lead.unknowns.some((item) => /Instagram/.test(item))); assert.equal(lead.communicationQuality.bookingAccessibility, "weak"); assert.match(lead.mainCommercialGap, /percurso/); assert.match(lead.whyContactThisLead, /negócio local/); });

test("score, readiness inputs and copy remain commercially coherent", () => { const lead = buildLeadIntelligence({ name: "Barbearia Central", niche: "Barbearias", confirmedBusiness: true, municipality: "Aveiro", instagramUrl: "https://instagram.com/barbearia", phone: "912345678", website: "https://barbearia.pt", hasBooking: false, hasCta: false, confidence: "medium" }); assert.ok(lead.commercialScore >= 70); assert.equal(lead.confidence, "medium"); assert.match(lead.initialMessage, /Uneed Soluções Digitais/); assert.match(lead.initialMessage, /desde 39€ \+ IVA\/mês/); assert.match(lead.initialMessage, /sem fidelização/); assert.doesNotMatch(lead.initialMessage, /—|LEADS START/); assert.ok(lead.followUp1.length < lead.initialMessage.length); });

test("structured commercial outputs never render as object Object", () => { const rendered = formatStructuredValue({ label: "Sem marcação", evidence: "CTA não encontrado" }); assert.equal(rendered, "Sem marcação"); assert.doesNotMatch(rendered, /\[object Object\]/); });
