const test = require("node:test");
const assert = require("node:assert/strict");
const { AIGateway } = require("../uneed-os/gateway");
const { LocalEvidenceProvider, AIProvider } = require("../uneed-os/providers");
const { MissionEngine } = require("../uneed-os/mission-engine");
const { MissionRepository } = require("../uneed-os/repository");
const { MissionRunner } = require("../uneed-os/runner");
const { listSkills } = require("../uneed-os/skills");
const { transition } = require("../uneed-os/state-machine");
const { Tool, ToolExecutor } = require("../uneed-os/tools");

function fixture({ providers = [new LocalEvidenceProvider()], maxSteps = 10, retryBaseMs = 0 } = {}) {
  const holder = { value: { missions: [] } };
  const repository = new MissionRepository({ readStore: () => structuredClone(holder.value), writeStore: (next) => { holder.value = structuredClone(next); } });
  const gateway = new AIGateway({ providers, routes: { FAST: providers.map((item) => item.id), SMART: providers.map((item) => item.id) } });
  const discover = { research: async (lead) => ({ pack: { schemaVersion: "1.0.0", companyIdentity: { name: lead.companyName }, knownData: { name: lead.companyName, contacts: { email: lead.clientEmail }, catalog: lead.services || [] }, businessSummary: lead.companyName, services: [], targetMarket: null, digitalPresence: { website: null, socialProfiles: [], googlePresence: null }, websiteSignals: null, facts: [], observations: [], inferences: [], opportunities: [], evidence: [], unknowns: ["Website"], conflicts: [], warnings: [], confidence: "low", researchedAt: new Date().toISOString(), freshness: "new" }, trace: [{ toolId: "read_crm", input: {}, resultCount: 1, durationMs: 1, cost: 0, costStatus: "actual" }], toolEstimatedCost: 0, toolCost: 0, toolCostStatus: "actual", durationMs: 1, partial: false }) };
  return { holder, repository, engine: new MissionEngine({ gateway, repository, discover, maxSteps, retryBaseMs }) };
}
async function create(engine, patch = {}) { return (await engine.create({ objective: "Qualificar Clínica Aurora", targetId: "lead-1", requestedBy: "user-1", input: { lead: { companyName: "Clínica Aurora", clientName: "Ana", clientEmail: "ana@example.test", services: [{ name: "LEADS FLOW", selected: true }] } }, ...patch })).mission; }
async function claimAndRun(engine, repository, worker = "worker-1", at) { const claimed = await repository.claimNext(worker, at); assert.ok(claimed); return engine.executeClaimed(claimed, worker); }

test("registry preserves v1.0 history and activates v1.1 Skills", () => { assert.deepEqual(listSkills().map((skill) => skill.id), ["research-company", "qualify-lead", "prepare-outreach"]); assert.ok(listSkills().every((skill) => skill.version === "1.1.0" && !skill.allowedTools.includes("send_email"))); assert.equal(listSkills({ includeHistorical: true }).filter((skill) => skill.version === "1.0.0").length, 3); });

test("creation is asynchronous, persisted as queued and independent of request/browser", async () => { const { holder, engine } = fixture(); const mission = await create(engine); assert.equal(mission.status, "queued"); const newRepository = new MissionRepository({ readStore: () => structuredClone(holder.value), writeStore: (next) => { holder.value = structuredClone(next); } }); assert.equal((await newRepository.get(mission.id, "user-1")).status, "queued"); });

test("claim is exclusive and records worker, heartbeat and attempt", async () => { const { engine, repository } = fixture(); await create(engine); const first = await repository.claimNext("worker-a"); const second = await repository.claimNext("worker-b"); assert.equal(first.workerId, "worker-a"); assert.equal(first.attempt, 1); assert.ok(first.heartbeatAt); assert.equal(second, null); });

test("status machine rejects arbitrary transitions", () => { assert.throws(() => transition({ status: "completed" }, "running"), /Transição inválida/); assert.equal(transition({ status: "draft" }, "queued").status, "queued"); });

test("steps persist checkpoints and Mission yields at Francisco Gate", async () => { const { engine, repository } = fixture(); const mission = await create(engine); const result = await claimAndRun(engine, repository); assert.equal(result.status, "waiting_approval"); assert.equal(result.steps.filter((step) => step.skillId).every((step) => step.status === "completed"), true); assert.equal(result.steps.at(-1).status, "pending"); assert.ok(result.events.some((item) => item.type === "approval.requested")); assert.equal((await repository.get(mission.id)).status, "waiting_approval"); });

test("research-only Mission completes with Research Pack and no approval step", async () => { const { engine, repository } = fixture(); const mission = await create(engine, { type: "research_company", autonomyLevel: "OBSERVE" }); const result = await claimAndRun(engine, repository); assert.equal(result.status, "completed"); assert.equal(result.steps.length, 1); assert.equal(result.result.research.schemaVersion, "1.0.0"); assert.equal(result.events.some((item) => item.type === "approval.requested"), false); });

test("approval persists, requeues and resumes without repeating Skills", async () => { const { engine, repository } = fixture(); const mission = await create(engine); await claimAndRun(engine, repository); const approved = await engine.decide(mission.id, { approved: true, decidedBy: "user-1" }); assert.equal(approved.status, "queued"); const result = await claimAndRun(engine, repository, "worker-2"); assert.equal(result.status, "completed"); assert.deepEqual(result.steps.filter((step) => step.skillId).map((step) => step.attempt), [1, 1, 1]); assert.equal(result.steps.at(-1).output.sideEffectExecuted, false); });

test("rejection completes without queuing or external action", async () => { const { engine, repository } = fixture(); const mission = await create(engine); await claimAndRun(engine, repository); const result = await engine.decide(mission.id, { approved: false, decidedBy: "user-1" }); assert.equal(result.status, "completed"); assert.match(result.events.at(-1).summary, /não executada/); });

test("queued cancellation is final and running cancellation is cooperative", async () => { const first = fixture(); const queued = await create(first.engine); assert.equal((await first.engine.cancel(queued.id, "user-1")).status, "cancelled"); const second = fixture(); const running = await create(second.engine); const claimed = await second.repository.claimNext("worker-1"); await second.engine.cancel(running.id, "user-1"); assert.equal((await second.engine.executeClaimed(claimed, "worker-1")).status, "cancelled"); });

test("retryable provider failure retries with limit then fails audibly", async () => { class Down extends AIProvider { constructor() { super(); this.id = "down"; this.model = "test"; } supports() { return true; } estimateCost() { return 0; } async execute() { const error = new Error("provider_error:503"); error.status = 503; throw error; } } const { engine, repository } = fixture({ providers: [new Down()] }); const mission = await create(engine, { maxAttempts: 2 }); const once = await claimAndRun(engine, repository); assert.equal(once.status, "queued"); assert.equal(once.lastError.code, "AI_UNAVAILABLE"); const twice = await claimAndRun(engine, repository, "worker-2", new Date(Date.now() + 100)); assert.equal(twice.status, "failed"); assert.equal(twice.attempt, 2); });

test("stale recovery fails closed to avoid silent duplicate side effects", async () => { const { engine, repository } = fixture(); await create(engine); const claimed = await repository.claimNext("dead-worker", new Date(Date.now() - 300000)); const runner = new MissionRunner({ engine, repository, staleMs: 1000, logger: { warn() {}, info() {}, error() {} } }); const recovered = await runner.recoverStale(); assert.equal(recovered[0].id, claimed.id); assert.equal(recovered[0].status, "failed"); assert.equal(recovered[0].error.code, "STALE_WORKER"); });

test("budget is checked before provider call", async () => { let calls = 0; class Costly extends AIProvider { constructor() { super(); this.id = "costly"; } supports() { return true; } estimateCost() { return 2; } async execute() { calls += 1; } } const { engine, repository } = fixture({ providers: [new Costly()] }); await create(engine, { maxCost: 1 }); const result = await claimAndRun(engine, repository); assert.equal(result.status, "failed"); assert.equal(result.error.code, "AI_BUDGET_EXCEEDED"); assert.equal(calls, 0); });

test("max steps stops future agentic loops", async () => { const { engine, repository } = fixture({ maxSteps: 2 }); await create(engine); const result = await claimAndRun(engine, repository); assert.equal(result.status, "failed"); assert.equal(result.error.code, "MAX_STEPS_EXCEEDED"); assert.equal(result.currentStepCount, 2); });

test("invalid structured output is non-retryable", async () => { class Invalid extends AIProvider { constructor() { super(); this.id = "invalid"; } supports() { return true; } estimateCost() { return 0; } async execute() { return { output: {}, cost: 0, usage: { calls: 1 } }; } } const { engine, repository } = fixture({ providers: [new Invalid()] }); await create(engine); const result = await claimAndRun(engine, repository); assert.equal(result.status, "failed"); assert.equal(result.error.code, "AI_BAD_RESPONSE"); assert.equal(result.attempt, 1); });

test("active duplicate is reused but historical completed Mission permits a new run", async () => { const { engine, repository } = fixture(); const first = await create(engine); const duplicate = await engine.create({ objective: "Outra", targetId: "lead-1", requestedBy: "user-1", input: { lead: {} } }); assert.equal(duplicate.duplicate, true); assert.equal(duplicate.mission.id, first.id); await claimAndRun(engine, repository); await engine.decide(first.id, { approved: false, decidedBy: "user-1" }); const fresh = await create(engine); assert.notEqual(fresh.id, first.id); });

test("owner permissions protect read, execution, cancellation and approval", async () => { const { engine, repository } = fixture(); const mission = await create(engine); assert.equal(await repository.get(mission.id, "user-2"), null); await assert.rejects(() => engine.cancel(mission.id, "user-2")); const claimed = await repository.claimNext("worker-1"); await assert.rejects(() => engine.executeClaimed(claimed, "worker-2"), /claim/); });

test("side-effect Tool requires permission and idempotency key and replays safely", async () => { let calls = 0; const records = new Map(); class SendTool extends Tool { constructor() { super({ id: "send", hasSideEffects: true }); } async execute() { calls += 1; return { sent: true }; } } const executor = new ToolExecutor({ tools: [new SendTool()], idempotencyStore: { get: (key) => records.get(key), set: (key, value) => records.set(key, value) } }); await assert.rejects(() => executor.execute({ toolId: "send", allowedTools: [] }), /não permitida/); await assert.rejects(() => executor.execute({ toolId: "send", allowedTools: ["send"] }), /idempotency/); const first = await executor.execute({ toolId: "send", allowedTools: ["send"], idempotencyKey: "mission:step:send" }); const replay = await executor.execute({ toolId: "send", allowedTools: ["send"], idempotencyKey: "mission:step:send" }); assert.equal(first.replayed, false); assert.equal(replay.replayed, true); assert.equal(calls, 1); });

test("gateway can fall back after normalized retryable provider failure", async () => { class Down extends AIProvider { constructor() { super(); this.id = "down"; } supports() { return true; } estimateCost() { return 0; } async execute() { const error = new Error("down"); error.status = 503; throw error; } } const gateway = new AIGateway({ providers: [new Down(), new LocalEvidenceProvider()], routes: { FAST: ["down", "local-evidence"] } }); const result = await gateway.execute({ task: "research-company", quality: "FAST", capabilitiesRequired: ["structured_output"], budget: 1, allowFallback: true, context: { lead: { companyName: "Teste" } }, outputSchema: {} }); assert.equal(result.provider, "local-evidence"); });
