(function initCommercialCore(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.UNEED_COMMERCIAL_CORE = api;
})(typeof window !== "undefined" ? window : null, function commercialCoreFactory() {
  const SCHEMA_VERSION = "commercial-core-v0.1";
  const WON_PROPOSAL_STATUSES = new Set(["Aceite", "Em desenvolvimento", "Concluído", "Faturado"]);
  const PROPOSAL_STAGES = { "Novo pedido": "NEW", "Orçamento enviado": "PROPOSAL", "Follow-up": "CONTACTED", Aceite: "WON", "Em desenvolvimento": "WON", Concluído: "WON", Faturado: "WON", Perdido: "LOST" };
  const INSTAGRAM_STAGES = { "Por fazer": "NEW", "Mensagem IG enviada": "CONTACTED", "Follow up WhatsApp": "CONTACTED", "Break up por telefone ou WhatsApp": "CONTACTED", "Pediu demonstração": "ENGAGED", "Cliente ativo": "WON", "Não deu cliente": "LOST" };
  const SOURCE_VALUES = Object.freeze(["automated_lead_factory", "instagram_prospecting", "website_form", "referral", "diagnostic", "google", "manual", "email_outreach", "whatsapp", "other"]);
  const CHANNEL_VALUES = Object.freeze(["instagram", "email", "whatsapp", "phone", "website", "meeting", "other"]);

  function id() { return globalThis.crypto?.randomUUID?.() || `core-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
  function clean(value) { return String(value || "").trim(); }
  function key(value) { return clean(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]/g, ""); }
  function email(value) { return clean(value).toLowerCase(); }
  function phone(value) { return clean(value).replace(/\D/g, "").replace(/^351/, ""); }
  function url(value) { try { const parsed = new URL(clean(value)); return ["http:","https:"].includes(parsed.protocol) ? parsed.href : ""; } catch { return ""; } }
  function domain(value) { try { return new URL(url(value)).hostname.replace(/^www\./, "").toLowerCase(); } catch { return ""; } }
  function instagramHandle(value) { return clean(value).toLowerCase().replace(/^https?:\/\/(www\.)?instagram\.com\//, "").replace(/[/?#].*$/, "").replace(/^@/, ""); }
  function now(value) { return value || new Date().toISOString(); }
  function sourceFromLegacy(value, instagram = false) { const source = key(value); if (instagram || source === "instagram") return "instagram_prospecting"; if (source.includes("refer")) return "referral"; if (source.includes("website")) return "website_form"; if (source.includes("whatsapp")) return "whatsapp"; if (source.includes("email")) return "email_outreach"; if (source.includes("google")) return "google"; if (source.includes("diagn")) return "diagnostic"; if (!source || source === "outro") return "manual"; return "other"; }
  function channelFromSource(source) { return source === "instagram_prospecting" ? "instagram" : source === "website_form" ? "website" : source === "whatsapp" ? "whatsapp" : source === "email_outreach" ? "email" : "other"; }
  function identitySignals(input = {}) { return { domain: domain(input.companyWebsite || input.website), instagram: instagramHandle(input.instagramUrl || input.instagram_url), email: email(input.companyEmail || input.email || input.clientEmail), phone: phone(input.companyPhone || input.phone || input.clientPhone), nif: key(input.nif || input.clientNif), name: key(input.companyName || input.commercialName || input.fiscalName || input.name), location: key(input.location) }; }
  function companySignals(company = {}) { return identitySignals({ companyWebsite: company.website, instagramUrl: company.instagramUrl, companyEmail: company.email, companyPhone: company.phone, nif: company.nif, companyName: company.name, location: company.location }); }
  function strongMatches(company, signals) { const existing = companySignals(company); return ["domain","instagram","email","phone","nif"].some((field) => signals[field] && existing[field] === signals[field]) || Boolean(signals.name && signals.location && existing.name === signals.name && existing.location === signals.location); }
  function potentialMatches(companies, signals) { return companies.filter((company) => { const existing = companySignals(company); return signals.name && existing.name === signals.name && !strongMatches(company, signals); }).map((company) => company.id); }
  function findOrCreateCompany(state, input, legacyRef) {
    const signals = identitySignals(input); const matches = state.companies.filter((company) => strongMatches(company, signals));
    if (matches.length === 1) return matches[0];
    const createdAt = now(input.createdAt || input.created_at); const company = { id: id(), name: clean(input.companyName || input.commercialName || input.fiscalName || input.name || "Empresa por identificar"), legalName: clean(input.legalName || input.fiscalName), website: url(input.companyWebsite || input.website), instagramUrl: url(input.instagramUrl || input.instagram_url), facebookUrl: url(input.facebookUrl || input.facebook_url), linkedinUrl: url(input.linkedinUrl || input.linkedin_url), bookingUrl: url(input.bookingUrl || input.booking_url), phone: clean(input.companyPhone || input.phone || input.clientPhone), email: clean(input.companyEmail || input.email || input.clientEmail), location: clean(input.location), nif: clean(input.nif || input.clientNif), notes: clean(input.notes || input.internalNotes), clientSince: null, potentialDuplicateOf: [...new Set([...potentialMatches(state.companies, signals), ...matches.map((item) => item.id)])], legacyRefs: legacyRef ? [legacyRef] : [], createdAt, updatedAt: now(input.updatedAt || input.updated_at || createdAt) };
    state.companies.push(company); return company;
  }
  function appendLegacyRef(company, legacyRef) { if (!legacyRef) return; company.legacyRefs ||= []; if (!company.legacyRefs.includes(legacyRef)) company.legacyRefs.push(legacyRef); }
  function updateCompany(company, input = {}) { const values = { name: clean(input.companyName || input.commercialName || input.name), legalName: clean(input.legalName || input.fiscalName), website: url(input.companyWebsite || input.website), instagramUrl: url(input.instagramUrl || input.instagram_url), facebookUrl: url(input.facebookUrl || input.facebook_url), linkedinUrl: url(input.linkedinUrl || input.linkedin_url), bookingUrl: url(input.bookingUrl || input.booking_url), phone: clean(input.companyPhone || input.phone), email: clean(input.companyEmail || input.email), location: clean(input.location), nif: clean(input.nif || input.clientNif), notes: clean(input.notes || input.internalNotes) }; for (const [field, value] of Object.entries(values)) if (value) company[field] = value; company.updatedAt = now(input.updatedAt || input.updated_at || company.updatedAt); return company; }
  function findOrCreateContact(state, company, input, legacyRef) { const contactEmail = email(input.clientEmail || input.email); const contactPhone = phone(input.clientPhone || input.phone); const contactName = key(input.clientName || input.contactPerson); let contact = state.contacts.find((item) => item.companyId === company.id && ((contactEmail && email(item.email) === contactEmail) || (contactPhone && phone(item.phone) === contactPhone) || (contactName && key(item.name) === contactName))); if (!contact && (contactName || contactEmail || contactPhone)) { contact = { id: id(), companyId: company.id, name: clean(input.clientName || input.contactPerson), role: clean(input.role || input.representativeRole), email: clean(input.clientEmail || input.email), phone: clean(input.clientPhone || input.phone), preferredChannel: clean(input.preferredChannel), notes: "", legacyRefs: legacyRef ? [legacyRef] : [], createdAt: now(input.createdAt), updatedAt: now(input.updatedAt || input.createdAt) }; state.contacts.push(contact); } else if (contact) { if (clean(input.clientName || input.contactPerson)) contact.name = clean(input.clientName || input.contactPerson); if (clean(input.clientEmail || input.email)) contact.email = clean(input.clientEmail || input.email); if (clean(input.clientPhone || input.phone)) contact.phone = clean(input.clientPhone || input.phone); contact.updatedAt = now(input.updatedAt || contact.updatedAt); if (legacyRef) { contact.legacyRefs ||= []; if (!contact.legacyRefs.includes(legacyRef)) contact.legacyRefs.push(legacyRef); } } return contact || null; }
  function ensureLead(state, seed) { let lead = seed.legacyProposalId ? state.leads.find((item) => item.legacyProposalId === seed.legacyProposalId) : state.leads.find((item) => item.legacyInstagramProspectId === seed.legacyInstagramProspectId); if (!lead) { lead = { id: id(), companyId: seed.companyId, contactId: seed.contactId || null, source: seed.source, channel: seed.channel, status: seed.status || "NEW", owner: null, score: seed.score ?? null, lastContactAt: seed.lastContactAt || null, nextActionAt: seed.nextActionAt || null, nextActionType: seed.nextActionType || null, followUpStatus: seed.followUpStatus || null, notes: seed.notes || "", legacyProposalId: seed.legacyProposalId || null, legacyInstagramProspectId: seed.legacyInstagramProspectId || null, createdAt: seed.createdAt, updatedAt: seed.updatedAt }; state.leads.push(lead); } else Object.assign(lead, { companyId: seed.companyId, contactId: seed.contactId || lead.contactId || null, source: seed.source, channel: seed.channel, status: seed.status || lead.status, score: seed.score ?? lead.score ?? null, lastContactAt: seed.lastContactAt || lead.lastContactAt || null, nextActionAt: seed.nextActionAt || lead.nextActionAt || null, nextActionType: seed.nextActionType || lead.nextActionType || null, followUpStatus: seed.followUpStatus || lead.followUpStatus || null, notes: seed.notes || lead.notes || "", updatedAt: seed.updatedAt }); return lead; }
  function ensureOpportunity(state, proposal, company, lead) { let opportunity = state.opportunities.find((item) => item.legacyProposalId === proposal.id); if (!opportunity) { opportunity = { id: id(), companyId: company.id, leadId: lead.id, title: clean(proposal.opportunityCategory || proposal.companyName || proposal.clientName || "Oportunidade"), stage: PROPOSAL_STAGES[proposal.status] || "NEW", estimatedValue: null, serviceInterest: clean(proposal.opportunityCategory), probability: null, nextAction: clean(proposal.followupDate), legacyProposalId: proposal.id, createdAt: now(proposal.createdAt), updatedAt: now(proposal.updatedAt || proposal.createdAt) }; state.opportunities.push(opportunity); } else Object.assign(opportunity, { companyId: company.id, leadId: lead.id, stage: PROPOSAL_STAGES[proposal.status] || opportunity.stage, nextAction: clean(proposal.followupDate), updatedAt: now(proposal.updatedAt) }); return opportunity; }
  function migrateProposal(state, proposal) { const ref = `proposal:${proposal.id}`; let company = state.companies.find((item) => item.id === proposal.companyId); if (!company) company = findOrCreateCompany(state, { ...proposal, website: proposal.companyWebsite }, ref); else updateCompany(company, { ...proposal, website: proposal.companyWebsite, companyPhone: "", companyEmail: "" }); appendLegacyRef(company, ref); const contact = state.contacts.find((item) => item.id === proposal.contactId) || findOrCreateContact(state, company, proposal, ref); const source = sourceFromLegacy(proposal.leadSource); const lead = ensureLead(state, { companyId: company.id, contactId: contact?.id, source, channel: channelFromSource(source), status: PROPOSAL_STAGES[proposal.status] || "NEW", nextActionAt: proposal.followupDate || null, followUpStatus: proposal.status === "Follow-up" ? "pending" : null, notes: proposal.internalNotes || "", legacyProposalId: proposal.id, createdAt: now(proposal.createdAt), updatedAt: now(proposal.updatedAt || proposal.createdAt) }); const opportunity = ensureOpportunity(state, proposal, company, lead); Object.assign(proposal, { companyId: company.id, contactId: contact?.id || null, leadId: lead.id, opportunityId: opportunity.id, companyWebsite: proposal.companyWebsite || company.website || "" }); if (WON_PROPOSAL_STATUSES.has(proposal.status)) company.clientSince ||= proposal.closedDate || proposal.updatedAt || proposal.createdAt || new Date().toISOString(); for (const activity of proposal.activities || []) { if (!state.activities.some((item) => item.legacyRef === `proposal:${proposal.id}:activity:${activity.id}`)) state.activities.push({ id: id(), companyId: company.id, contactId: contact?.id || null, leadId: lead.id, opportunityId: opportunity.id, proposalId: proposal.id, type: activity.type || "note", summary: activity.note || "", channel: null, occurredAt: now(activity.createdAt), legacyRef: `proposal:${proposal.id}:activity:${activity.id}`, createdAt: now(activity.createdAt) }); } }
  function migrateInstagramProspect(state, prospect) { const ref = `instagramProspect:${prospect.id}`; const companyInput = { companyName: prospect.name, website: prospect.officialWebsite || prospect.website, instagramUrl: prospect.instagramUrl, phone: prospect.phone, location: [prospect.municipality, prospect.district].filter(Boolean).join(", "), notes: prospect.notes, createdAt: prospect.createdAt, updatedAt: prospect.updatedAt }; let company = state.companies.find((item) => item.id === prospect.companyId); if (!company) company = findOrCreateCompany(state, companyInput, ref); else updateCompany(company, companyInput); appendLegacyRef(company, ref); const lead = ensureLead(state, { companyId: company.id, source: prospect.source || "instagram_prospecting", channel: prospect.primaryChannel || "instagram", status: INSTAGRAM_STAGES[prospect.status] || "NEW", score: prospect.commercialScore ?? prospect.score ?? null, lastContactAt: prospect.lastContactAt || null, nextActionAt: prospect.nextActionAt || null, nextActionType: prospect.nextActionType || null, followUpStatus: ["Follow up WhatsApp","Break up por telefone ou WhatsApp"].includes(prospect.status) ? "pending" : null, notes: prospect.notes || "", legacyInstagramProspectId: prospect.id, createdAt: now(prospect.createdAt), updatedAt: now(prospect.updatedAt || prospect.createdAt) }); Object.assign(lead, { readiness: prospect.readiness || lead.readiness || "not_researched", discoverySource: prospect.discoverySource || lead.discoverySource || null, latestResearchMissionId: prospect.latestResearchMissionId || lead.latestResearchMissionId || null }); Object.assign(prospect, { companyId: company.id, leadId: lead.id }); if (prospect.status === "Cliente ativo") company.clientSince ||= prospect.updatedAt || prospect.createdAt || new Date().toISOString(); }
  function migrateContract(state, contract) { let proposal = state.proposals.find((item) => item.id === contract.proposalId); if (!proposal) proposal = state.proposals.find((item) => { const company = state.companies.find((entry) => entry.id === item.companyId); return company && strongMatches(company, identitySignals(contract)); }); let company = proposal && state.companies.find((item) => item.id === proposal.companyId); if (!company) company = state.companies.find((item) => item.id === contract.companyId); if (!company) company = findOrCreateCompany(state, contract, `contract:${contract.id}`); appendLegacyRef(company, `contract:${contract.id}`); contract.companyId = company.id; contract.proposalId ||= proposal?.id || null; contract.opportunityId ||= proposal?.opportunityId || null; if (contract.status === "Aceite") company.clientSince ||= contract.acceptedAt || contract.updatedAt || contract.createdAt || new Date().toISOString(); }
  function linkTicket(state, ticket) { let company = state.companies.find((item) => item.id === (ticket.companyId || ticket.company_id)); if (!company) { const signals = identitySignals(ticket); const matches = state.companies.filter((item) => strongMatches(item, signals)); if (matches.length === 1) company = matches[0]; } ticket.companyId = company?.id || null; ticket.contactId ||= ticket.contact_id || null; ticket.projectId ||= ticket.project_id || null; return ticket; }
  function migrateState(state = {}) { state.commercialCore ||= {}; state.companies ||= []; state.contacts ||= []; state.leads ||= []; state.opportunities ||= []; state.activities ||= []; state.projects ||= []; state.proposals ||= []; state.instagramProspects ||= []; state.contracts ||= []; state.tickets ||= []; for (const proposal of state.proposals) migrateProposal(state, proposal); for (const prospect of state.instagramProspects) migrateInstagramProspect(state, prospect); for (const contract of state.contracts) migrateContract(state, contract); for (const ticket of state.tickets) linkTicket(state, ticket); state.commercialCore = { schemaVersion: SCHEMA_VERSION, migratedAt: state.commercialCore.migratedAt || new Date().toISOString(), lastValidatedAt: new Date().toISOString() }; return state; }
  function companyContext(state, leadId) { const lead = state.leads?.find((item) => item.id === leadId); const company = lead && state.companies?.find((item) => item.id === lead.companyId); const contact = lead?.contactId && state.contacts?.find((item) => item.id === lead.contactId); return company && lead ? { company: structuredClone(company), lead: structuredClone(lead), contact: contact ? structuredClone(contact) : null } : null; }
  return { SCHEMA_VERSION, SOURCE_VALUES, CHANNEL_VALUES, PROPOSAL_STAGES, INSTAGRAM_STAGES, migrateState, linkTicket, companyContext };
});
