(function(root){
  'use strict';
  const niches={
    geral:{name:'Outro / geral',services:'Serviços ou produtos que quer apresentar',team:'Equipa e funções (se relevante)',sector:'O que distingue o seu negócio?',hint:'Conte-nos em poucas palavras quem ajuda e o que faz melhor.'},
    cabeleireiro:{name:'Cabeleireiro / barbearia',services:'Serviços de cabelo e preços que pretende divulgar',team:'Profissionais e especialidades',sector:'Como prefere receber pedidos dos clientes?',hint:'Por exemplo: telefone, WhatsApp, marcação presencial. Indique também marcas ou técnicas a destacar.'},
    estetica:{name:'Estética / beleza',services:'Tratamentos e serviços a apresentar',team:'Profissionais e especialidades',sector:'Que tratamentos ou diferenciais quer destacar?',hint:'Indique apenas informação pública aprovada. Não envie fichas de clientes.'},
    clinica:{name:'Clínica / saúde',services:'Especialidades e serviços da clínica',team:'Equipa, especialidades e credenciais públicas',sector:'Informação prática para novos utentes',hint:'Por exemplo: acessibilidade, convenções ou forma de marcar. Não envie dados clínicos nem dados de utentes.'},
    veterinaria:{name:'Clínica veterinária',services:'Serviços veterinários e espécies atendidas',team:'Equipa e áreas de atuação',sector:'Urgências e informações para os tutores',hint:'Indique se há urgências, o respetivo horário e contacto público. Não envie processos clínicos.'},
    restaurante:{name:'Restaurante / café',services:'Tipo de cozinha, menus e serviços',team:'Espaços e capacidade (se relevante)',sector:'Reservas, takeaway e necessidades alimentares',hint:'Indique como recebe reservas, links da ementa e informações que queira publicar.'},
    b2b:{name:'Fornecedores / serviços B2B',services:'Produtos, serviços e áreas de fornecimento',team:'Contacto comercial e departamentos',sector:'O que precisa de saber para preparar um orçamento?',hint:'Por exemplo: quantidades, zona de entrega ou tipo de cliente. Não envie dados confidenciais de terceiros.'}
  };
  const labels={businessName:'Nome do negócio',contact:'Pessoa de contacto',email:'Email',phone:'Telefone',taxId:'NIF',billingAddress:'Morada de faturação',businessAddress:'Morada / área de atendimento',socialLinks:'Redes sociais',siteType:'Situação do site',currentUrl:'Site atual',domain:'Domínio',services:'Serviços / oferta',hours:'Horários',team:'Equipa',sectorNotes:'Informação do setor',keep:'O que manter',remove:'O que retirar',changes:'O que pretende criar',newPages:'Páginas e conteúdos',references:'Referências visuais',contentLinks:'Links de conteúdos',notes:'Notas',contentHelp:'Preciso de ajuda com os conteúdos',accepted:'Confirmação'};
  function nicheKey(value){const s=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(niches[s])return s;if(/veterin/.test(s))return 'veterinaria';if(/cabeleir|barbear/.test(s))return 'cabeleireiro';if(/estetic|beleza|beauty/.test(s))return 'estetica';if(/clinic|saude|fisioter|dent/.test(s))return 'clinica';if(/restaur|cafe|pastel/.test(s))return 'restaurante';if(/b2b|forneced|distribuid/.test(s))return 'b2b';return 'geral';}
  function pending(record){const a=record.answers||{},o=record.offer||{},c=record.checks||{},out=[];for(const key of ['contact','phone','taxId','billingAddress'])if(!String(a[key]||'').trim())out.push(labels[key]);if(!a.email&&!o.email)out.push('Email');if(o.requiresContent&&!c.content){if(!a.services)out.push('Serviços / oferta');if(!a.hours)out.push('Horários (se aplicável)');if(a.contentHelp)out.push('Apoio UNEED na preparação dos conteúdos');if(!(record.images||[]).some(x=>x.status==='ready')&&!a.contentLinks)out.push('Imagens / conteúdos a combinar com a UNEED');}return out;}
  function prospectSeed(lead){const c=lead.customer||{};return {company:c.companyName||lead.name||'',contact:c.contactName||lead.contactName||'',email:c.email||lead.email||'',phone:c.phone||lead.phone||'',taxId:c.nif||'',billingAddress:c.address||'',niche:c.niche||lead.niche||'',companyId:lead.companyId||'',leadId:lead.leadId||lead.id||''};}
  function nicheOptions(values=[]){return {...Object.fromEntries(Object.entries(niches).map(([id,n])=>[id,n.name])),...Object.fromEntries(values.filter(Boolean).filter(v=>!niches[v]).map(v=>[v,v]))};}
  const api={niches,labels,nicheKey,pending,prospectSeed,nicheOptions};if(typeof module!=='undefined')module.exports=api;if(root)root.UNEED_KICKOFF_INTAKE=api;
})(typeof window!=='undefined'?window:null);
