/* Kickoff management uses its own API; never writes the CRM state snapshot. */
const KickoffsUI=(()=>{
  let items=[],loading=false;
  const labels={draft:'Rascunho',linked:'Link criado',sent:'Convite enviado',started:'Em preenchimento',submitted:'Em validação UNEED',completed:'Concluído',cancelled:'Cancelado'};
  const products={presenca:'UNEED Presença',marcacoes:'Marcações',leads:'Leads'};
  const h=s=>escapeHtml(String(s??''));
  const money=n=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(n);
  async function api(body) {
    const client=getSupabaseClient(),token=client?(await client.auth.getSession()).data.session?.access_token:null;
    if(!token)throw Error('Inicie sessão no CRM para gerir kickoffs.');
    const r=await fetch('/api/kickoffs',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
    const p=await r.json().catch(()=>({error:'Resposta inválida do servidor.'}));if(!r.ok)throw Error(p.error);return p;
  }
  function message(s){document.querySelector('#kickoffsMessage').textContent=s;}
  async function load() {
    if(loading)return;loading=true;message('A carregar kickoffs…');
    try {let offset=0;items=[];for(;;){const client=getSupabaseClient(),token=(await client.auth.getSession()).data.session?.access_token;
      const r=await fetch('/api/kickoffs?offset='+offset,{headers:{Authorization:'Bearer '+token}});const p=await r.json();if(!r.ok)throw Error(p.error);items.push(...p.items);if(p.items.length<100)break;offset+=100;}
      render();message(items.length+' kickoffs · pagamentos e mandatos confirmados manualmente pela UNEED.');
      const target=location.hash.match(/^#kickoffs=([a-f0-9-]{36})$/)?.[1];if(target){history.replaceState(null,'','#kickoffs');const item=items.find(x=>x.id===target);if(item)detail(item);}
    }catch(e){message(e.message);}finally{loading=false;}
  }
  function options(obj,v){return Object.entries(obj).map(([k,s])=>`<option value="${h(k)}" ${k===v?'selected':''}>${h(s)}</option>`).join('');}
  function render() {
    const host=document.querySelector('#kickoffsList'),search=document.querySelector('#kickoffsSearch').value.toLowerCase(),product=document.querySelector('#kickoffsProduct').value,status=document.querySelector('#kickoffsStatus').value,niche=document.querySelector('#kickoffsNiche').value;
    document.querySelector('#kickoffsNiche').innerHTML='<option value="">Todos os nichos</option>'+options(UNEED_KICKOFF_INTAKE.nicheOptions(items.map(x=>x.data.offer.niche)),niche);
    const filtered=items.filter(r=>(!product||r.data.offer.product===product)&&(!status||r.data.status===status)&&(!niche||r.data.offer.niche===niche)&&JSON.stringify([r.data.offer.company,r.data.offer.email,r.id]).toLowerCase().includes(search.replace(/^uneed-/,'')));
    host.innerHTML=filtered.map(r=>{const o=r.data.offer,c=r.data.checks;return `<article class="panel kickoff-tile"><div class="panel-heading"><h3>${h(o.company)}</h3><span class="status-pill">${h(labels[r.data.status])}</span></div><p>${h(o.planName)} · ${h(UNEED_KICKOFF_INTAKE.nicheOptions()[o.niche]||o.niche)} · UNEED-${h(r.id.slice(0,8).toUpperCase())}</p><strong>${money(o.total.net)} ${o.period==='monthly'?'/ mês':o.period==='annual'?'/ ano':'pontual'} · líquido</strong><p class="card-meta">Criado ${new Date(r.created_at).toLocaleDateString('pt-PT')} · Última atividade ${new Date(r.updated_at).toLocaleString('pt-PT')} · Etapa ${r.data.stage}/6</p><p>Pagamento: ${c.payment?'confirmado':o.initial.net?'pendente':'N/A'} · Débito: ${o.requiresDebit?(c.debit?'confirmado':'pendente'):'N/A'} · Conteúdos: ${o.requiresContent?(c.content?'validados':'pendentes'):'N/A'}</p><button class="button primary" data-open="${r.id}">Abrir e gerir</button></article>`;}).join('')||(items.length?'<p>Nenhum kickoff corresponde a estes filtros.</p>':'<p>Ainda não criou kickoffs. Use «Criar kickoff» ou abra «Preparar kickoff» na ficha do lead em PROSPEÇÃO. Os seletores acima servem apenas para filtrar esta lista.</p>');
    host.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>detail(items.find(x=>x.id===b.dataset.open)));
  }
  function dialog(title,body) {
    const d=document.createElement('dialog');d.className='customer-dialog kickoff-dialog';d.innerHTML=`<div class="panel-heading"><h2>${h(title)}</h2><button class="button ghost" data-close>Fechar</button></div>${body}`;
    document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();return d;
  }
  function fromProposal(p) {
    const type=UNEED_CUSTOMERS.typeOf(p);if(['high_ticket','other'].includes(type))throw Error('Este cliente usa o kickoff de projeto. O gerador de subscrições suporta Presença, Marcações e Leads.');
    const product={presence:'presenca',bookings:'marcacoes',leads:'leads'}[type],cat=UNEED_KICKOFF_CATALOG.commercialCatalog[product];
    const rows=(p.services||[]).filter(x=>x.selected),base=rows[0];if(!base)throw Error('A proposta não tem serviços selecionados.');
    if(Number(p.discount)>0)throw Error('A proposta tem desconto. Prepare a oferta manualmente com os valores acordados; não vamos ignorar o desconto na importação.');
    const period=base.billing==='Mensal'?'monthly':base.billing==='Anual'?'annual':'once';
    if(rows.some(x=>x.billing!==base.billing))throw Error('A proposta mistura periodicidades. Reveja a oferta antes de criar o kickoff; não vamos omitir linhas automaticamente.');
    if(rows.slice(1).some(x=>!cat.addons.includes(String(x.id).replace(/^addon:/,''))))throw Error('A proposta tem serviços adicionais personalizados. Não podem ser convertidos em extras automaticamente.');
    const plan=cat.plans[base.id]?base.id:cat.defaultPlan;
    return {product,plan,company:p.companyName,contact:p.clientName,email:p.clientEmail,phone:p.clientPhone,taxId:p.clientNif,billingAddress:p.customer?.address||'',niche:p.niche||p.customer?.niche||'',basePrice:Number(base.price)*Number(base.qty||1),period,
      vat:p.vatMode??0,retention:p.withholdingMode??0,taxNotes:p.customer?.taxNotes||'',initialBase:'',paymentMethod:'bank_transfer',requiresDebit:period==='monthly',requiresContent:true,
      proposalId:p.id,companyId:p.companyId||'',leadId:p.leadId||'',addons:rows.slice(1).map(x=>({id:String(x.id).replace(/^addon:/,''),unitPrice:x.price,quantity:x.qty,languages:x.languages||[]}))};
  }
  function editor(seed={},record=null) {
    const C=UNEED_KICKOFF_CATALOG;let current={product:'presenca',plan:'presenca-essencial',basePrice:39,vat:0,retention:0,initialBase:'',period:'monthly',paymentMethod:'bank_transfer',requiresDebit:true,requiresContent:true,addons:[],...seed};
    const field=(key,label,type='text',required=false)=>`<label>${label}<input name="${key}" type="${type}" value="${h(current[key]??'')}" ${required?'required':''} ${type==='number'?'min="0" step="0.01"':''}></label>`;
    const d=dialog(record?'Editar rascunho':'Criar kickoff',`<form><label>Preencher a partir de cliente/proposta<select data-source><option value="">Preenchimento manual</option>${(state.proposals||[]).map(p=>`<option value="${h(p.id)}">${h(p.companyName||p.clientName)} · ${h(p.clientEmail||'')}</option>`).join('')}</select></label><div class="form-grid">${field('company','Empresa','text',true)}${field('contact','Contacto','text',true)}${field('email','Email','email',true)}${field('phone','Telefone','tel',true)}${field('taxId','NIF')}${field('billingAddress','Morada de faturação')}<label>Produto<select name="product">${options(products,current.product)}</select></label><label>Plano<select name="plan"></select></label>${field('niche','Nicho')}<label>Periodicidade<select name="period">${options({monthly:'Mensal',annual:'Anual',once:'Pontual'},current.period)}</select></label>${field('basePrice','Preço base acordado (€)','number',true)}${field('vat','IVA (%)','number',true)}${field('retention','Retenção (%)','number',true)}${field('taxNotes','Enquadramento fiscal / isenção')}${field('initialBase','Adjudicação — valor base (€)','number',true)}<label>Pagamento inicial<select name="paymentMethod">${options({bank_transfer:'Transferência',mbway:'MB WAY'},current.paymentMethod)}</select></label>${field('gocardless','Link específico GoCardless','url')}${field('collectionDay','Dia de cobrança (1–28)','number')}${field('deadline','Prazo estimado')}</div><fieldset><legend>Extras da oferta · preços acordados</legend><div data-addons></div></fieldset><p class="card-meta">Assistente Guiado: opções e percursos preparados. Assistente Inteligente: perguntas livres com base na informação aprovada do negócio.</p><label><input type="checkbox" name="requiresDebit" ${current.requiresDebit?'checked':''}> Débito direto obrigatório</label><label><input type="checkbox" name="requiresContent" ${current.requiresContent?'checked':''}> Conteúdos obrigatórios</label><label>Introdução para o cliente<textarea name="intro">${h(current.intro||'')}</textarea></label><label>Notas internas (nunca visíveis ao cliente)<textarea name="internalNotes">${h(current.internalNotes||'')}</textarea></label><p data-total class="customer-total"></p><p data-error role="alert"></p><button class="button primary" type="submit">Guardar rascunho</button></form>`);
    const f=d.querySelector('form');
    if(seed.company)f.querySelector('[data-source] option').textContent='Dados pré-preenchidos · '+seed.company;
    // Keep the commercial editor for internal use, but lead with only the essentials.
    const intro=document.createElement('p');intro.className='kickoff-intro';intro.textContent='Escolha o cliente e o setor. Os contactos, dados de faturação e conteúdos em falta são pedidos diretamente ao cliente, pelo seu link.';f.prepend(intro);
    const grid=f.querySelector('.form-grid');
    const section=(title)=>{const el=document.createElement('details');const heading=document.createElement('summary');heading.textContent=title;el.append(heading);grid.after(el);return el;};
    const known=section('Dados já conhecidos · opcionais');
    for(const name of ['contact','phone','taxId','billingAddress']){f.elements[name].required=false;known.append(f.elements[name].closest('label'));}
    f.elements.email.required=false;f.elements.email.closest('label').firstChild.textContent='Email para convite (opcional)';
    const commercial=section('Condições já acordadas · confirmar valores e impostos');
    for(const name of ['period','basePrice','vat','retention','taxNotes','paymentMethod','collectionDay','deadline','requiresDebit','requiresContent'])commercial.append(f.elements[name].closest('label'));
    f.elements.initialBase.closest('label').firstChild.textContent='Primeiro pagamento acordado (€ sem IVA; 0 se não há)';
    const extras=document.createElement('details');extras.open=current.addons.length>0;extras.innerHTML='<summary>Extras já contratados</summary><p>Apenas serviços já acordados. Não são sugeridos extras ao cliente.</p>';extras.append(f.querySelector('fieldset'));commercial.append(extras);extras.querySelector('legend').textContent='Serviços adicionais acordados';
    f.querySelector('.card-meta')?.remove();
    for(const name of ['intro','internalNotes'])known.append(f.elements[name].closest('label'));
    const nicheInput=f.elements.niche,nicheSelect=document.createElement('select');nicheSelect.name='niche';nicheSelect.innerHTML=options(Object.fromEntries(Object.entries(UNEED_KICKOFF_INTAKE.niches).map(([id,n])=>[id,n.name])),UNEED_KICKOFF_INTAKE.nicheKey(current.niche));if(current.niche&&!UNEED_KICKOFF_INTAKE.niches[current.niche]&&UNEED_KICKOFF_INTAKE.nicheKey(current.niche)==='geral'){const custom=new Option(current.niche,current.niche,true,true);nicheSelect.add(custom);}nicheInput.replaceWith(nicheSelect);
    f.querySelector('[type=submit]').textContent='Guardar e preparar link';
    function plans(){f.elements.plan.innerHTML=options(Object.fromEntries(Object.entries(C.commercialCatalog[f.elements.product.value].plans).map(([id,p])=>[id,p.name])),current.plan);}
    function addons(){d.querySelector('[data-addons]').innerHTML=C.commercialCatalog[f.elements.product.value].addons.map(id=>{const def=C.addonCatalog[id],a=current.addons.find(x=>x.id===id);return `<div class="kickoff-addon"><label><input type="checkbox" data-addon="${id}" ${a?'checked':''}> ${h(def.name)}${def.description?`<small>${h(def.description)}</small>`:''}</label><label>Preço/unidade<input type="number" min="0" step="0.01" data-price="${id}" value="${h(a?.unitPrice??def.unitPrice??'')}" placeholder="A confirmar"></label>${def.type==='quantity'?`<label>Quantidade<input type="number" min="1" max="20" step="1" data-qty="${id}" value="${a?.quantity||1}"></label>`:def.type==='languages'?`<div>${C.allowedLanguages.map(l=>`<label><input type="checkbox" data-language="${id}" value="${l}" ${a?.languages?.includes(l)?'checked':''}> ${l.toUpperCase()}</label>`).join('')}</div>`:'<span>Por período da oferta</span>'}</div>`;}).join('');}
    function values(){return {...current,...Object.fromEntries(new FormData(f)),requiresDebit:f.elements.requiresDebit.checked,requiresContent:f.elements.requiresContent.checked,addons:[...d.querySelectorAll('[data-addon]:checked')].map(el=>({id:el.dataset.addon,unitPrice:d.querySelector(`[data-price="${el.dataset.addon}"]`).value,quantity:d.querySelector(`[data-qty="${el.dataset.addon}"]`)?.value||1,languages:[...d.querySelectorAll(`[data-language="${el.dataset.addon}"]:checked`)].map(x=>x.value)}))};}
    function preview(){try{const v=values();if(v.addons.some(a=>a.unitPrice===''))throw Error('Confirme os preços dos extras selecionados.');const base=Number(v.basePrice)+v.addons.reduce((s,a)=>s+Number(a.unitPrice)*(a.id==='extra-language'?a.languages.length:Number(a.quantity)),0),t=UNEED_CUSTOMERS.fiscal(base,v.vat,v.retention),i=UNEED_CUSTOMERS.fiscal(Number(v.initialBase),v.vat,v.retention);d.querySelector('[data-total]').textContent=`Oferta: base ${money(t.base)} + IVA ${money(t.vat)} = ${money(t.total)} − retenção ${money(t.retention)} = ${money(t.net)} líquido. Adjudicação: ${money(i.net)} líquido.`;}catch(e){d.querySelector('[data-total]').textContent=e.message;}}
    plans();addons();preview();f.oninput=preview;
    f.elements.product.onchange=()=>{current.product=f.elements.product.value;current.plan=C.commercialCatalog[current.product].defaultPlan;current.addons=[];plans();addons();f.elements.basePrice.value=C.commercialCatalog[current.product].plans[current.plan].price;preview();};
    f.elements.plan.onchange=()=>{f.elements.basePrice.value=C.commercialCatalog[f.elements.product.value].plans[f.elements.plan.value].price;preview();};
    d.querySelector('[data-source]').onchange=e=>{try{const p=state.proposals.find(p=>p.id===e.target.value);if(p){const v=fromProposal(p);d.close();editor(v,record);}}catch(err){d.querySelector('[data-error]').textContent=err.message;}};
    f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{const p=await api({action:record?'update':'create',id:record?.id,revision:record?.revision,offer:values()});d.close();await load();detail(p.kickoff);}catch(err){d.querySelector('[data-error]').textContent=err.message;}finally{b.disabled=false;}};
  }
  function detail(r) {
    const o=r.data.offer,c=r.data.checks,d=dialog(o.company,`<p>${h(labels[r.data.status])} · ${h(o.planName)} · ${money(o.total.net)} líquido</p><p>${h(o.email)} · ${h(o.phone)}</p><p>Link válido até: ${r.data.expiresAt?new Date(r.data.expiresAt).toLocaleString('pt-PT'):'não emitido'}</p><div class="deal-actions">${r.data.status==='draft'?'<button data-action="edit" class="button ghost">Editar</button><button data-action="issue" class="button primary">Gerar link</button>':'<button data-action="link" class="button primary">Copiar link</button><button data-action="send" class="button ghost">Enviar convite</button>'}<button data-action="preview" class="button ghost">Pré-visualizar</button><button data-action="duplicate" class="button ghost">Duplicar</button><button data-action="revoke" class="button ghost">Desativar</button></div><p data-feedback role="status"></p><label>Validade ao gerar (dias)<input data-days type="number" min="1" max="365" value="30"></label><fieldset><legend>Validação manual UNEED</legend>${Object.entries({payment:'Adjudicação confirmada',debit:'Mandato GoCardless confirmado',content:'Conteúdos validados',validated:'Validação final UNEED',execution:'Execução iniciada'}).map(([key,label])=>`<label><input data-check="${key}" type="checkbox" ${c[key]?'checked':''}> ${label}${key==='debit'&&!o.requiresDebit?' (não aplicável)':key==='payment'&&!o.initial.net?' (não aplicável)':''}</label>`).join('')}<button class="button primary" data-action="checks">Guardar validações</button></fieldset><label>Link GoCardless<input type="url" data-gc value="${h(o.gocardless)}"></label><button class="button ghost" data-action="debitLink">Atualizar link GoCardless</button><details><summary>Informação recebida</summary>${Object.entries(r.data.answers).map(([k,v])=>`<p><strong>${h(UNEED_KICKOFF_INTAKE.labels[k]||k)}</strong>: ${h(typeof v==='boolean'?(v?'Sim':'Não'):v)}</p>`).join('')||'<p>Ainda sem respostas.</p>'}</details><details><summary>Notas internas</summary><p>${h(o.internalNotes)}</p></details><details><summary>Emails e histórico</summary><p>Aceite = aceite pelo servidor SMTP, não confirmação de entrega. Pendente/desconhecido exige revisão antes de reenviar.</p>${Object.entries(r.data.mail).map(([k,v])=>`<p>${h(k)}: ${h(v.status)} · ${h(v.at)}</p>`).join('')}<button class="button ghost" data-action="customer">Reenviar confirmação ao cliente</button><button class="button ghost" data-action="admin">Reenviar notificação interna</button>${r.data.events.map(e=>`<p>${h(new Date(e.at).toLocaleString('pt-PT'))} · ${h(e.type)}</p>`).join('')}</details>`);
    const missing=document.createElement('section');missing.className='kickoff-pending';const pending=UNEED_KICKOFF_INTAKE.pending(r.data);missing.innerHTML='<h3>Informação a completar</h3>'+(pending.length?'<ul>'+pending.map(label=>`<li>${h(label)}</li>`).join('')+'</ul>':'<p>Sem dados em falta nesta checklist. Confirme os conteúdos antes de iniciar.</p>');d.querySelector('[data-feedback]').after(missing);
    const attachments=document.createElement('details');attachments.open=true;
    attachments.innerHTML=`<summary>Imagens do cliente (${(r.data.images||[]).filter(x=>x.status==='ready').length})</summary>${(r.data.images||[]).map(x=>`<p>${h(x.name)} · ${x.status==='ready'?`${x.width} × ${x.height} px · ${(x.size/1048576).toFixed(1)} MB`:h(x.error||x.status)} ${x.status==='ready'?`<button class="button ghost" data-image="${x.id}">Descarregar original</button>`:''}</p>`).join('')||'<p>Ainda sem imagens.</p>'}`;
    d.append(attachments);attachments.querySelectorAll('[data-image]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const result=await api({action:'image-download',id:r.id,fileId:b.dataset.image});const a=document.createElement('a');a.href=result.downloadUrl;a.rel='noopener noreferrer';a.referrerPolicy='no-referrer';a.click();}catch(e){d.querySelector('[data-feedback]').textContent=e.message;}finally{b.disabled=false;}});
    d.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{
      const action=b.dataset.action,feedback=d.querySelector('[data-feedback');
      if(action==='edit'){d.close();editor(o,r);return;}
      if(action==='revoke'&&!confirm('Desativar este link? O registo e o histórico serão preservados.'))return;
      const send=['send','customer','admin'].includes(action);if(send&&!confirm('Enviar um email real? Se já houve tentativa, o reenvio pode duplicar uma mensagem entregue.'))return;
      b.disabled=true;feedback.textContent='A processar…';
      try {
        const result=await api({action:send?'send':action,id:r.id,revision:r.revision,days:Number(d.querySelector('[data-days]').value),url:d.querySelector('[data-gc]').value,checks:Object.fromEntries([...d.querySelectorAll('[data-check]')].map(e=>[e.dataset.check,e.checked])),kind:action==='send'?'invite':action,confirmRetry:send});
        if(action==='link'){try{await navigator.clipboard.writeText(result.url);feedback.textContent='Link copiado.';}catch{feedback.textContent=result.url;}return;}
        if(action==='preview'){const p=result.kickoff.offer;dialog('Pré-visualização da oferta',`<p>Pré-visualização interna · não envia nem regista atividade do cliente.</p><h3>${h(p.company)}</h3><p>${h(p.intro)}</p><p>${h(p.planName)} · ${h(p.niche)}</p><p>Base ${money(p.total.base)} + IVA ${money(p.total.vat)} − retenção ${money(p.total.retention)} = ${money(p.total.net)} líquido</p>${p.addons.map(a=>`<p>${h(a.name)} × ${a.quantity}: ${money(a.subtotal)}</p>`).join('')}<p>Adjudicação: ${money(p.initial.net)}</p><p>Prazo: ${h(p.deadline)}</p>`);feedback.textContent='Pré-visualização aberta.';return;}
        d.close();await load();detail(result.kickoff);
      }catch(e){feedback.textContent=e.message;}finally{b.disabled=false;}
    });
  }
  function init(){document.querySelector('#kickoffsCreate').onclick=()=>editor();document.querySelector('#kickoffsRefresh').onclick=load;['Search','Product','Status','Niche'].forEach(k=>document.querySelector('#kickoffs'+k).addEventListener(k==='Search'?'input':'change',render));document.querySelector('#kickoffsStatus').innerHTML='<option value="">Todos os estados</option>'+options(labels);}
  function fromClient(p){try{const seed=fromProposal(p);switchView('kickoffs');editor(seed);}catch(e){alert(e.message);}}
  function fromProspect(lead){if(!lead)return;try{
    const seed=UNEED_KICKOFF_INTAKE.prospectSeed(lead);
    const p=(state.proposals||[]).find(p=>p.id===lead.customer?.proposalId||p.sourceProspectId===lead.id);
    if(lead.acquisitionStrategy==='high_ticket'&&(!p||['high_ticket','other'].includes(UNEED_CUSTOMERS.typeOf(p)))){
      dialog('Kickoff de projeto · '+seed.company,'<p>'+h(seed.company)+' · '+h(seed.niche)+'</p><p>Este lead é High Ticket. O gerador de subscrições não deve aplicar-lhe um plano Presença. Mantenha as condições da proposta e use o roteiro de projeto.</p><a class="button primary" href="/kickoff-project.html" target="_blank" rel="noopener">Abrir roteiro de projeto</a>');return;
    }
    const terms=p?fromProposal(p):lead.customer?.rows?.length?fromProposal({customer:lead.customer,services:lead.customer.rows,companyName:seed.company,vatMode:lead.customer.vatMode,withholdingMode:lead.customer.withholdingMode}):{};
    switchView('kickoffs');editor({...seed,...terms,company:terms.company||seed.company,contact:terms.contact||seed.contact,email:terms.email||seed.email,phone:terms.phone||seed.phone,niche:terms.niche||seed.niche,companyId:terms.companyId||seed.companyId,leadId:terms.leadId||seed.leadId});
  }catch(e){alert(e.message);}}
  return {load,init,fromClient,fromProspect};
})();
document.addEventListener('DOMContentLoaded',()=>{KickoffsUI.init();if(location.hash.startsWith('#kickoffs'))switchView('kickoffs');});
