const { RuntimeError } = require("./errors");
const { evidence, ReadCrmTool, SearchWebTool, FetchPublicPageTool, InspectWebsiteTool, DiscoverSocialProfilesTool, PageClient } = require("./discover-tools");
const { ToolExecutor } = require("./tools");

class DiscoverService {
  constructor({ searchProvider, limits = {}, pageClient = new PageClient() }) { this.limits = { maxSearches: Number(limits.maxSearches ?? 2), maxPages: Number(limits.maxPages ?? 3), maxDepth: Number(limits.maxDepth ?? 1) }; const tools = [new ReadCrmTool(), new FetchPublicPageTool({ pageClient }), new InspectWebsiteTool({ pageClient }), new DiscoverSocialProfilesTool()]; if (searchProvider?.supports()) tools.push(new SearchWebTool({ provider: searchProvider })); this.executor = new ToolExecutor({ tools }); this.searchProvider = searchProvider; }
  async research(subject, { budget = 1 } = {}) {
    const started = Date.now(); const trace = []; const warnings = []; let toolCost = 0; let toolEstimatedCost = 0; let costUnknown = false; const run = async (toolId, input, allowedTools) => { const at = Date.now(); const estimate = toolId === "search_web" ? this.searchProvider?.estimateCost(input) : 0; if (estimate == null && toolId === "search_web") costUnknown = true; else { toolEstimatedCost += Number(estimate || 0); if (toolEstimatedCost > budget) throw new RuntimeError("AI_BUDGET_EXCEEDED", "Orçamento estimado de Tools excedido."); } const result = await this.executor.execute({ toolId, input, allowedTools, context: {} }); if (result.cost == null || result.costStatus === "unknown") costUnknown = true; else toolCost += Number(result.cost || 0); if (!costUnknown && toolCost > budget) throw new RuntimeError("AI_BUDGET_EXCEEDED", "Orçamento de Tools excedido."); trace.push({ toolId, input: toolId === "search_web" ? { query: input.query, maxResults: input.maxResults } : { url: input.url }, resultCount: result.results?.length ?? result.profiles?.length ?? 1, durationMs: Date.now() - at, estimatedCost: estimate ?? null, cost: result.cost ?? null, costStatus: result.costStatus || "unknown", cached: Boolean(result.cached) }); return result; };
    const lead = subject?.lead || subject || {}; const company = subject?.company || null; const contact = subject?.contact || null; const allowed = ["read_crm","search_web","fetch_public_page","inspect_website","discover_social_profiles"]; const crm = (await run("read_crm", { lead, company, contact, services: subject?.services }, allowed)).data; let searchResults = [];
    if (this.searchProvider?.supports() && this.limits.maxSearches > 0 && crm.name) { try { searchResults = (await run("search_web", { query: `"${crm.name}" ${crm.location}`.trim(), maxResults: 6 }, allowed)).results; } catch (error) { if (error.code === "AI_BUDGET_EXCEEDED") throw error; warnings.push(`Pesquisa indisponível: ${error.code || "SEARCH_ERROR"}. O Research Pack foi concluído com os dados e páginas acessíveis.`); } } else warnings.push("Pesquisa web não configurada; resultados limitados ao website conhecido.");
    let website = crm.website || searchResults.map((item) => item.url).find((url) => !/facebook|instagram|linkedin|youtube|tiktok/i.test(url)) || ""; let inspection = null; const pages = [];
    if (website) { try { const inspected = await run("inspect_website", { url: website }, allowed); inspection = inspected.inspection; pages.push(inspected.page); website = inspected.inspection.url; warnings.push(...inspection.signals); const relevant = inspected.inspection.principalPages.slice(0, Math.max(0, this.limits.maxPages - 1)); for (const link of relevant) { try { pages.push((await run("fetch_public_page", { url: link.url }, allowed)).page); } catch (error) { warnings.push(`Página não obtida: ${link.url} (${error.code || "FETCH_ERROR"})`); } } } catch (error) { warnings.push(`Website não inspecionado: ${error.code || "FETCH_ERROR"}`); }
    } else warnings.push("Website oficial não confirmado.");
    const social = (await run("discover_social_profiles", { websiteLinks: inspection?.socialLinks || [], searchResults, crm }, allowed)).profiles; const evidenceItems = [];
    if (website && inspection) { evidenceItems.push(evidence({ url: website, title: inspection.title, fact: `Website respondeu com HTTP ${inspection.status}.`, confidence: "high" })); evidenceItems.push(evidence({ url: website, title: inspection.title, fact: inspection.https ? "Website usa HTTPS." : "Website observado sem HTTPS.", confidence: "high" })); if (inspection.mobileViewport) evidenceItems.push(evidence({ url: website, title: inspection.title, fact: "Página inclui meta viewport para dispositivos móveis.", confidence: "high" })); }
    for (const profile of social) evidenceItems.push(evidence({ url: profile.url, title: profile.platform, fact: `Perfil ${profile.platform} associado através de ${profile.source}.`, confidence: profile.confidence }));
    const dedupedEvidence = [...new Map(evidenceItems.map((item) => [`${item.sourceUrl}:${item.fact}`, item])).values()]; const observations = []; const conflicts = []; if (inspection && !inspection.booking) observations.push({ statement: "Não foi encontrado um caminho explícito de marcação nas páginas analisadas.", evidenceIds: dedupedEvidence.filter((item) => item.sourceUrl === website).map((item) => item.id), scope: "pages_analysed" }); if (inspection && !inspection.forms) observations.push({ statement: "Não foram encontrados formulários na homepage analisada.", evidenceIds: dedupedEvidence.filter((item) => item.sourceUrl === website).map((item) => item.id), scope: "homepage" }); if (crm.email && inspection?.contacts.emails[0] && crm.email.toLowerCase() !== inspection.contacts.emails[0].toLowerCase()) { conflicts.push({ field: "email", values: [{ value: crm.email, source: "crm" }, { value: inspection.contacts.emails[0], source: website }], resolution: "unresolved" }); warnings.push("Contacto de email difere entre CRM e website."); }
    const inferences = observations.map((item) => ({ statement: item.statement.includes("marcação") ? "A ausência observada de marcação pode criar fricção, se o negócio depender de agendamentos." : "A ausência observada de formulários pode limitar captação direta pelo website.", basedOnEvidenceIds: item.evidenceIds, confidence: "low" })); const opportunities = inferences.map((item) => ({ recommendation: item.statement.includes("agendamentos") ? "Validar necessidade de uma solução UNEED com marcações." : "Validar necessidade de captação de leads no website.", basedOnInference: item.statement }));
    const unknowns = ["Preços", "Número de colaboradores", "Volume de negócio", "Sistema interno utilizado", "Pessoa decisora", "Orçamento disponível"]; if (!inspection) unknowns.push("Estado técnico atual do website"); if (!social.length) unknowns.push("Perfis sociais oficiais");
    let confidence = dedupedEvidence.length >= 4 && inspection ? "high" : dedupedEvidence.length >= 2 ? "medium" : "low"; if (conflicts.length && confidence === "high") confidence = "medium"; return { pack: { schemaVersion: "1.0.0", companyIdentity: { name: crm.name, location: crm.location || null }, knownData: { name: crm.name, location: crm.location || null, website: website || null, contacts: { email: conflicts.some((item) => item.field === "email") ? null : crm.email || inspection?.contacts.emails[0] || null, phone: crm.phone || inspection?.contacts.phones[0] || null }, catalog: crm.catalog }, businessSummary: pages[0]?.content.metaDescription || pages[0]?.content.title || crm.name, services: pages.flatMap((page) => page.content.headings).slice(0, 20), targetMarket: null, digitalPresence: { website: website || null, socialProfiles: social, googlePresence: null }, websiteSignals: inspection ? { https: inspection.https, mobile: inspection.mobileViewport, contactPaths: inspection.ctas, forms: inspection.forms > 0, booking: inspection.booking, ecommerce: inspection.ecommerce, quoteRequest: inspection.quoteRequest, whatsapp: inspection.whatsapp, socialLinks: inspection.socialLinks } : null, facts: dedupedEvidence.map((item) => ({ statement: item.fact, evidenceIds: [item.id] })), observations, inferences, opportunities, evidence: dedupedEvidence, unknowns: [...new Set([...unknowns, ...conflicts.map((item) => `${item.field} em conflito entre fontes`)])], conflicts, warnings, confidence, researchedAt: new Date().toISOString(), freshness: trace.some((item) => item.cached) ? "reuse_recent" : "new" }, trace, toolEstimatedCost, toolCost: costUnknown ? null : toolCost, toolCostStatus: costUnknown ? "unknown" : "actual", durationMs: Date.now() - started, partial: warnings.length > 0 };
  }
}

module.exports = { DiscoverService };
